name: Lint TPV config files
# env:
#   TPV_VERSION: '1.2.0'
# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
on:
  pull_request:
    branches: [ main ]
    paths:
      - tools.yml

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # number of commits to fetch. 0 indicates all history for all branches and tags
    # Set up python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: pip
    - name: Install dependencies
      run: pip install -r workflows/requirements.txt
    # Install python dependencies for check_files script
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install total-perspective-vortex==$TPV_VERSION pyyaml galaxy-data
    # Run check files script
    - name: Run tpv lint on all vortex config files
      env:
        SETTING: github
      run: tpv lint tools.yml
